#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Thu Apr 18 11:10:34 EDT 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_15 -libname processing_system7_vip_v1_0_17 -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname axi_lite_ipif_v3_0_4 -libname v_tc_v6_2_7 -libname v_tc_v6_1_13 -libname v_vid_in_axi4s_v4_0_11 -libname v_axi4s_vid_out_v4_0_17 -libname xlconstant_v1_1_8 -libname lib_pkg_v1_0_3 -libname fifo_generator_v13_2_9 -libname lib_fifo_v1_0_18 -libname blk_mem_gen_v8_4_7 -libname lib_bmg_v1_0_16 -libname lib_srl_fifo_v1_0_3 -libname axi_datamover_v5_1_31 -libname axi_vdma_v6_3_17 -libname smartconnect_v1_0 -libname axi_register_slice_v2_1_29 -libname interrupt_control_v3_1_5 -libname axi_iic_v2_1_5 -libname axi_intc_v4_1_18 -libname xlconcat_v2_1_5 -libname axi_gpio_v2_0_31 -libname xbip_utils_v3_0_11 -libname c_reg_fd_v12_0_7 -libname xbip_dsp48_wrapper_v3_0_5 -libname xbip_pipe_v3_0_7 -libname xbip_dsp48_addsub_v3_0_7 -libname xbip_addsub_v3_0_7 -libname c_addsub_v12_0_16 -libname c_gate_bit_v12_0_7 -libname xbip_counter_v3_0_7 -libname c_counter_binary_v12_0_17 -libname axis_infrastructure_v1_1_1 -libname axis_data_fifo_v2_0_11 -libname generic_baseblocks_v2_1_1 -libname axi_data_fifo_v2_1_28 -libname axi_crossbar_v2_1_30 -libname axi_protocol_converter_v2_1_29 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_15 processing_system7_vip_v1_0_17 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 axi_lite_ipif_v3_0_4 v_tc_v6_2_7 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_11 v_axi4s_vid_out_v4_0_17 xlconstant_v1_1_8 lib_pkg_v1_0_3 fifo_generator_v13_2_9 lib_fifo_v1_0_18 blk_mem_gen_v8_4_7 lib_bmg_v1_0_16 lib_srl_fifo_v1_0_3 axi_datamover_v5_1_31 axi_vdma_v6_3_17 smartconnect_v1_0 axi_register_slice_v2_1_29 interrupt_control_v3_1_5 axi_iic_v2_1_5 axi_intc_v4_1_18 xlconcat_v2_1_5 axi_gpio_v2_0_31 xbip_utils_v3_0_11 c_reg_fd_v12_0_7 xbip_dsp48_wrapper_v3_0_5 xbip_pipe_v3_0_7 xbip_dsp48_addsub_v3_0_7 xbip_addsub_v3_0_7 c_addsub_v12_0_16 c_gate_bit_v12_0_7 xbip_counter_v3_0_7 c_counter_binary_v12_0_17 axis_infrastructure_v1_1_1 axis_data_fifo_v2_0_11 generic_baseblocks_v2_1_1 axi_data_fifo_v2_1_28 axi_crossbar_v2_1_30 axi_protocol_converter_v2_1_29)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/adrian/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/home/adrian/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work processing_system7_vip_v1_0_17 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_processing_system7_0_0/sim/design_1_processing_system7_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ps7_0_100M_0/sim/design_1_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_2_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/0e63/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_v_tc_0_0/sim/design_1_v_tc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work v_tc_v6_1_13 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work v_vid_in_axi4s_v4_0_11 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/4705/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work v_axi4s_vid_out_v4_0_17 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/b7a6/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_v_axi4s_vid_out_0_0/sim/design_1_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/ClockGen.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsync.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/SyncAsyncReset.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/DVI_Constants.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/OutputSERDES.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/TMDS_Encoder.vhd" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d57c/src/rgb2dvi.vhd" \
  "../../../bd/design_1/ip/design_1_rgb2dvi_0_0/sim/design_1_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_8 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconstant_0_2/sim/design_1_xlconstant_0_2.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/AXIvideo2Mat.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Block_proc.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/fifo_w8_d2_A.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/fifo_w10_d2_A.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/fifo_w11_d2_A.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/fifo_w11_d3_A.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Mat2AXIvideo.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Resize.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Resize_opr_linear.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Resize_opr_linearbkb.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/Resize_opr_linearcud.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/scaleImage_mul_mug8j.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/scaleImage_sdiv_4dEe.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/scaleImage_sdiv_4eOg.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/scaleImage_udiv_2fYi.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/start_for_Mat2AXIhbi.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/start_for_Resize_U0.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/61f0/hdl/verilog/scaleImage.v" \
  "../../../bd/design_1/ip/design_1_scaleImage_0_1/sim/design_1_scaleImage_0_1.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/AXIvideo2Mat.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/Block_proc.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/CvtColor.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/Mat2AXIvideo.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/start_for_CvtColobkb.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/start_for_Mat2AXIcud.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1b7a/hdl/verilog/gray2rgb.v" \
  "../../../bd/design_1/ip/design_1_gray2rgb_0_0_1/sim/design_1_gray2rgb_0_0.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/47f5/hdl/verilog/axistream2axivideo.v" \
  "../../../bd/design_1/ip/design_1_axistream2axivideo_0_0/sim/design_1_axistream2axivideo_0_0.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filtebkb.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filtehbi.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filteibs.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filtejbC.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filter_AXILiteS_s_axi.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/8f65/hdl/verilog/convolution_filter.v" \
  "../../../bd/design_1/ip/design_1_convolution_filter_0_2/sim/design_1_convolution_filter_0_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/56d9/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_9 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_9 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_18 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/1531/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_7 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_bmg_v1_0_16 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/5c9c/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_3 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/02c4/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_31 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d786/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_vdma_v6_3_17 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_vdma_v6_3_17 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_vdma_0_0/sim/design_1_axi_vdma_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_48ac_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_48ac_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_48ac_arsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_48ac_rsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_48ac_awsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_48ac_wsw_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_48ac_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_48ac_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_48ac_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_48ac_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_48ac_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_48ac_sarn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_48ac_srn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_48ac_s01mmu_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_48ac_s01tr_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_48ac_s01sic_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_48ac_s01a2s_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_48ac_sawn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_48ac_swn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_48ac_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_48ac_m00s2a_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_48ac_m00arn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_48ac_m00rn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_48ac_m00awn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_48ac_m00wn_0.sv" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_48ac_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_48ac_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/bd_0/sim/bd_48ac.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_smartconnect_0_0/sim/design_1_smartconnect_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_5 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_iic_v2_1_5 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/0f29/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_iic_0_0/sim/design_1_axi_iic_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_intc_v4_1_18 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d764/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_intc_0_0/sim/design_1_axi_intc_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconcat_0_0/sim/design_1_xlconcat_0_0.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_31 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6fbe/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_gpio_0_0/sim/design_1_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/d250/hdl/verilog/ov7670_interface.v" \
  "../../../bd/design_1/ip/design_1_ov7670_interface_0_0/sim/design_1_ov7670_interface_0_0.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/e99f/hdl/verilog/LF_valid_to_AXIS.v" \
  "../../../bd/design_1/ip/design_1_LF_valid_to_AXIS_0_0/sim/design_1_LF_valid_to_AXIS_0_0.v" \
  "../../../bd/design_1/ip/design_1_xlconstant_0_3/sim/design_1_xlconstant_0_3.v" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c593/hdl/verilog/ov7670_LUMA_CHROMA.v" \
  "../../../bd/design_1/ip/design_1_ov7670_LUMA_CHROMA_0_0/sim/design_1_ov7670_LUMA_CHROMA_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_11 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/9836/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_reg_fd_v12_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/747b/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_wrapper_v3_0_5 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/e5f6/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c4f2/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_dsp48_addsub_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/9cc0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_addsub_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/641b/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_addsub_v12_0_16 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6c3a/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_gate_bit_v12_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7f53/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_counter_v3_0_7 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/0005/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work c_counter_binary_v12_0_17 -V93 $xmvhdl_opts \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f6d3/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_c_counter_binary_0_0/sim/design_1_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_1 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_data_fifo_v2_0_11 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/68dc/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_axis_data_fifo_0_0/sim/design_1_axis_data_fifo_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_1/sim/design_1_proc_sys_reset_0_1.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_1 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_28 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_30 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_29 $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/6b2b/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/7fb4/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/c2c6" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ipshared/434f/hdl" +incdir+"../../../../OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_convolution_filter_0_2/drivers/convolution_filter_v1_0/src" +incdir+"/home/adrian/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/adrian/github_repos/OV7670-PynqZ2/Progetto/OV7670-pynq/OV7670-pynq.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
