# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/github_repos/OV7670-PynqZ2/Progetto/OV7670-pynq/OV7670-pynq.srcs/sources_1/bd/design_1/ip/design_1_scaleImage_0_1/design_1_scaleImage_0_1.xci
# IP: The module: 'design_1_scaleImage_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/github_repos/OV7670-PynqZ2/Progetto/OV7670-pynq/OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_scaleImage_0_1/constraints/scaleImage_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_scaleImage_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adrian/github_repos/OV7670-PynqZ2/Progetto/OV7670-pynq/OV7670-pynq.srcs/sources_1/bd/design_1/ip/design_1_scaleImage_0_1/design_1_scaleImage_0_1.xci
# IP: The module: 'design_1_scaleImage_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/github_repos/OV7670-PynqZ2/Progetto/OV7670-pynq/OV7670-pynq.gen/sources_1/bd/design_1/ip/design_1_scaleImage_0_1/constraints/scaleImage_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_scaleImage_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
